CREATE DATABASE IF NOT EXISTS tutu;
DROP DATABASE IF EXISTS toto;
DROP DATABASE IF EXISTS titi;
USE tutu;

DROP TABLE IF EXISTS Persons;
CREATE TABLE IF NOT EXISTS Persons (
    ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LastName VARCHAR(50),
    FirstName VARCHAR(50),
    Adress VARCHAR(255),
    City VARCHAR(50)
);
CREATE TABLE IF NOT EXISTS Clients (
    ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Nom VARCHAR(50),
    Prénom VARCHAR(50),
    Email VARCHAR(50)
);


-- ALTER TABLE 